# Generated by Django 3.1.1 on 2022-05-06 03:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_formforsubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforsubmit',
            name='article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
