# Generated by Django 3.1.1 on 2022-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20220506_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforsubmit',
            name='headline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formforsubmit',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
