# Generated by Django 3.1.1 on 2022-05-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20220509_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formforsubmit',
            options={'verbose_name': 'Article'},
        ),
    ]
