# Generated by Django 4.0.4 on 2022-05-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='user',
        ),
    ]
