# Generated by Django 4.0.4 on 2022-05-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_tasksforoperations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksforoperations',
            options={'verbose_name': 'Task'},
        ),
    ]
