# Generated by Django 4.0.4 on 2022-05-19 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_tasksforoperations_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksforoperations',
            name='task',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
