# Generated by Django 4.0.4 on 2022-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_tasksforoperations_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksforoperations',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
