# Generated by Django 4.0.4 on 2022-05-19 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0017_alter_tasksforoperations_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksforoperations',
            old_name='status',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='tasksforoperations',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
