# Generated by Django 4.0.4 on 2022-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_tasksforoperations_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='formforsubmit',
            name='prev_img',
            field=models.ImageField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
