# Generated by Django 4.0.4 on 2022-05-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_formforsubmit_prev_img'),
        ('subscriptions', '0021_conversation_loaded'),
    ]

    operations = [
    ]
