# Generated by Django 4.0.4 on 2022-05-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_merge_20220522_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='seenByAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='seenByUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formforsubmit',
            name='prev_img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
