# Generated by Django 4.0.4 on 2022-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_sendmail_seenbyadmin_sendmail_seenbyuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='seenByAdmin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sendmail',
            name='seenByUser',
            field=models.BooleanField(default=True),
        ),
    ]
