# Generated by Django 4.0.4 on 2022-05-26 08:39

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0024_alter_sendmail_seenbyadmin_alter_sendmail_seenbyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fromAdmin', models.BooleanField(default=True)),
                ('seenByAdmin', models.BooleanField(default=True)),
                ('seenByUser', models.BooleanField(default=True)),
                ('timeSent', models.DateTimeField(default=datetime.datetime(2022, 5, 26, 14, 9, 35, 903984))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail',
            },
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='loaded',
            new_name='seenByAdmin',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='view',
            new_name='seenByUser',
        ),
        migrations.DeleteModel(
            name='sendmail',
        ),
    ]
