# Generated by Django 4.0.4 on 2022-05-26 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_messages_rename_loaded_conversation_seenbyadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='media',
            field=models.FileField(default=0, upload_to='message_media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 17, 17, 0, 402275)),
        ),
    ]
