# Generated by Django 4.0.4 on 2022-05-26 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_messages_media_alter_messages_timesent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='hasMedia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 19, 6, 33, 935834)),
        ),
    ]
