# Generated by Django 4.0.4 on 2022-05-26 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0027_messages_hasmedia_alter_messages_timesent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='media',
        ),
        migrations.AddField(
            model_name='messages',
            name='mediaUrl',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 22, 22, 10, 54542)),
        ),
    ]
