# Generated by Django 4.0.4 on 2022-05-26 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_remove_messages_media_messages_mediaurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='hasMedia',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='mediaUrl',
        ),
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 22, 48, 32, 989314)),
        ),
    ]
