# Generated by Django 4.0.4 on 2022-06-06 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0029_remove_messages_hasmedia_remove_messages_mediaurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 6, 17, 38, 512966)),
        ),
    ]
