# Generated by Django 4.0.4 on 2022-06-10 12:33

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0030_alter_messages_timesent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksforoperations',
            name='commentbyoperator',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 18, 3, 11, 265343)),
        ),
    ]
