# Generated by Django 4.0.4 on 2022-07-04 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0031_tasksforoperations_commentbyoperator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 8, 32, 56, 283124)),
        ),
    ]
