# Generated by Django 4.0.4 on 2022-07-04 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0032_alter_messages_timesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 11, 55, 41, 405711)),
        ),
    ]
