# Generated by Django 4.1.1 on 2022-09-30 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0035_alter_messages_timesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 15, 11, 15, 247910)),
        ),
    ]
