# Generated by Django 4.0.4 on 2022-10-01 05:10

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0035_alter_messages_timesent'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('task_description', models.CharField(max_length=255)),
                ('task_status', models.CharField(max_length=255)),
                ('task_date', models.DateTimeField()),
                ('proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('commentbyoperator', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 5, 10, 29, 596881)),
        ),
        migrations.DeleteModel(
            name='tasksforoperations',
        ),
    ]
