# Generated by Django 4.1.1 on 2022-10-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0036_alter_messages_timesent'),
        ('subscriptions', '0038_remove_task_description_remove_task_task_status_and_more'),
    ]

    operations = [
    ]
