# Generated by Django 4.1.1 on 2022-10-01 16:34

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0039_merge_20221001_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='commentbyoperator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='proof',
        ),
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 1, 22, 3, 59, 377152)),
        ),
        migrations.CreateModel(
            name='tasksubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('completed_on', models.DateTimeField(default=datetime.datetime(2022, 10, 1, 22, 3, 59, 392796))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Response',
            },
        ),
    ]
