# Generated by Django 4.0.4 on 2022-05-16 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='user',
            new_name='mUser',
        ),
        migrations.AddField(
            model_name='sendmail',
            name='messageList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.message'),
            preserve_default=False,
        ),
    ]
