# Generated by Django 4.0.4 on 2022-05-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_sendmail_messagelist_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='fromAdmin',
            field=models.BooleanField(default=True),
        ),
    ]
