# Generated by Django 4.0.4 on 2022-05-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_sendmail_fromadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='mUser',
            new_name='user',
        ),
    ]
