# Generated by Django 4.0.4 on 2022-05-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chat',
        ),
        migrations.AddField(
            model_name='conversation',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
