# Generated by Django 4.0.4 on 2022-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_formforsubmit_prev_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formforsubmit',
            name='prev_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
